version: "3.1"
services:
  postgres:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: actix
      POSTGRES_USER: actix
      POSTGRES_DB: actix
    ports:
    - 15432:5432
    deploy:
      resources:
        limits:
          memory: '512M'
          cpus: '1'
  todo-actix:
    build: .
    links:
      - postgres
    environment:
      SERVER.HOST: 0.0.0.0
      SERVER.PORT: 1313
      PG.USER: actix
      PG.PASSWORD: actix
      PG.HOST: postgres
      PG.PORT: 15432
      PG.DBNAME: actix
      PG.POOL.MAX_SIZE: 30
    deploy:
      resources:
        limits:
          memory: '512M'
          cpus: '1'
    ports:
      - 1313:1313